### ISSUE TITLE
nikto missing

### ISSUE THREAD

**Issue by pulsar-cyber** [madhuakula/hacker-container#2]
nikto is not available

**Comment by madhuakula** [comment]
Yes, looks like it's not working as tested. Thanks for the issue, I will fix this and update the docker image

**Comment by madhuakula** [comment]
Fixed the bug. Thanks once again @pulsar-cyber 

https://github.com/madhuakula/hacker-container/commit/e30d23ae6b1b7ee19aac74ae9c74d27384800b29

Closing the issue
